# This is vector search. It uses dense embeddings generated by the local Ollama model and performs a similarity search in PostgreSQL.

from typing import List
from ml.embedder import generate_embeddings
from db import search_dense_chunks

def dense_search(query: str, user_id: str, top_k: int = 5) -> List[dict]:    
    try:
        query_embeddings = generate_embeddings([query])
        if not query_embeddings:
            return []
            
        query_vector = query_embeddings[0]
    except Exception as e:
        raise RuntimeError(f"Failed to embed query: {e}")
        
    # Search the database using the new vector
    relevant_chunks = search_dense_chunks(
        user_id=user_id, 
        query_vector=query_vector, 
        top_k=top_k
    )
    
    return relevant_chunks